import asyncio
from database import init_db, add_internship

INTERNSHIPS = [
    #Яндекс
    {
        "company": "Яндекс",
        "title": "Стажёр-бэкенд-разработчик",
        "stack": "Python, C++, Go",
        "city": "Москва",
        "remote": 1,
        "salary": "от 60 000 ₽",
        "description": "Разработка сервисов Яндекса. Работа в команде с ментором, ревью кода, участие в продуктовых задачах.",
        "url": "https://yandex.ru/yaintern",
        "deadline": "30.06.2026",
    },
    {
        "company": "Яндекс",
        "title": "Стажёр-фронтенд-разработчик",
        "stack": "JavaScript, TypeScript, React",
        "city": "Москва",
        "remote": 1,
        "salary": "от 60 000 ₽",
        "description": "Разработка интерфейсов сервисов Яндекса. TypeScript, React, внутренние фреймворки.",
        "url": "https://yandex.ru/yaintern",
        "deadline": "30.06.2026",
    },
    {
        "company": "Яндекс",
        "title": "Стажёр Data Science",
        "stack": "Python, ML, PyTorch, SQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 60 000 ₽",
        "description": "Работа с данными и ML-моделями в продуктовых командах Яндекса.",
        "url": "https://yandex.ru/yaintern",
        "deadline": "30.06.2026",
    },
    {
        "company": "Яндекс",
        "title": "Стажёр-аналитик данных",
        "stack": "SQL, Python, BI",
        "city": "Москва",
        "remote": 1,
        "salary": "от 55 000 ₽",
        "description": "Аналитика продуктовых метрик, построение дашбордов, A/B-тесты.",
        "url": "https://yandex.ru/yaintern",
        "deadline": "30.06.2026",
    },
    # Сбер
    {
        "company": "Сбер",
        "title": "Стажёр Java-разработчик",
        "stack": "Java, Spring, Kafka",
        "city": "Москва",
        "remote": 0,
        "salary": "от 50 000 ₽",
        "description": "Разработка банковских сервисов на Java. Микросервисная архитектура, Kafka, PostgreSQL.",
        "url": "https://sbergraduate.ru",
        "deadline": "15.07.2026",
    },
    {
        "company": "Сбер",
        "title": "Стажёр DevOps / SRE",
        "stack": "Linux, Docker, Kubernetes, CI/CD",
        "city": "Москва",
        "remote": 0,
        "salary": "от 50 000 ₽",
        "description": "Поддержка инфраструктуры, автоматизация деплоя, мониторинг.",
        "url": "https://sbergraduate.ru",
        "deadline": "15.07.2026",
    },
    {
        "company": "Сбер",
        "title": "Стажёр Data Engineer",
        "stack": "Python, SQL, Spark, Hadoop",
        "city": "Москва",
        "remote": 0,
        "salary": "от 50 000 ₽",
        "description": "Построение ETL-пайплайнов и работа с Big Data.",
        "url": "https://sbergraduate.ru",
        "deadline": "15.07.2026",
    },
    # VK
    {
        "company": "VK",
        "title": "Стажёр C++ разработчик",
        "stack": "C++, Linux",
        "city": "Санкт-Петербург",
        "remote": 0,
        "salary": "от 55 000 ₽",
        "description": "Разработка высоконагруженных сервисов ВКонтакте и Mail.ru.",
        "url": "https://team.vk.company/internship",
        "deadline": "01.07.2026",
    },
    {
        "company": "VK",
        "title": "Стажёр Go-разработчик",
        "stack": "Go, gRPC, PostgreSQL",
        "city": "Санкт-Петербург",
        "remote": 1,
        "salary": "от 55 000 ₽",
        "description": "Микросервисы на Go для продуктов VK. gRPC, очереди сообщений.",
        "url": "https://team.vk.company/internship",
        "deadline": "01.07.2026",
    },
    {
        "company": "VK",
        "title": "Стажёр-тестировщик (QA)",
        "stack": "Python, Selenium, SQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 45 000 ₽",
        "description": "Автоматизация тестирования продуктов VK. Написание автотестов на Python.",
        "url": "https://team.vk.company/internship",
        "deadline": "01.07.2026",
    },
    # Т-Банк (Тинькофф)
    {
        "company": "Т-Банк",
        "title": "Стажёр Kotlin-разработчик",
        "stack": "Kotlin, Spring Boot, PostgreSQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 60 000 ₽",
        "description": "Разработка финтех-сервисов. Kotlin, Spring Boot, микросервисы.",
        "url": "https://education.tbank.ru",
        "deadline": "20.06.2026",
    },
    {
        "company": "Т-Банк",
        "title": "Стажёр iOS-разработчик",
        "stack": "Swift, UIKit, SwiftUI",
        "city": "Москва",
        "remote": 1,
        "salary": "от 55 000 ₽",
        "description": "Разработка мобильного приложения Т-Банка для iOS.",
        "url": "https://education.tbank.ru",
        "deadline": "20.06.2026",
    },
    {
        "company": "Т-Банк",
        "title": "Стажёр Android-разработчик",
        "stack": "Kotlin, Android, Jetpack Compose",
        "city": "Москва",
        "remote": 1,
        "salary": "от 55 000 ₽",
        "description": "Мобильная разработка под Android. Kotlin, Jetpack Compose, MVVM.",
        "url": "https://education.tbank.ru",
        "deadline": "20.06.2026",
    },
    {
        "company": "Т-Банк",
        "title": "Стажёр Python-разработчик",
        "stack": "Python, FastAPI, PostgreSQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 60 000 ₽",
        "description": "Backend-разработка на Python. FastAPI, asyncio, PostgreSQL.",
        "url": "https://education.tbank.ru",
        "deadline": "20.06.2026",
    },
    # Ozon
    {
        "company": "Ozon",
        "title": "Стажёр Go-разработчик",
        "stack": "Go, PostgreSQL, Kafka",
        "city": "Москва",
        "remote": 1,
        "salary": "от 50 000 ₽",
        "description": "Разработка микросервисов маркетплейса Ozon на Go.",
        "url": "https://job.ozon.ru",
        "deadline": "30.06.2026",
    },
    {
        "company": "Ozon",
        "title": "Стажёр-аналитик",
        "stack": "SQL, Python, Tableau",
        "city": "Москва",
        "remote": 1,
        "salary": "от 45 000 ₽",
        "description": "Продуктовая аналитика e-commerce. SQL, Python, дашборды.",
        "url": "https://job.ozon.ru",
        "deadline": "30.06.2026",
    },
    # Wildberries
    {
        "company": "Wildberries",
        "title": "Стажёр Go-разработчик",
        "stack": "Go, PostgreSQL, Redis",
        "city": "Москва",
        "remote": 0,
        "salary": "от 45 000 ₽",
        "description": "Бэкенд-разработка сервисов маркетплейса на Go.",
        "url": "https://wildberries.ru/career",
        "deadline": "15.07.2026",
    },
    {
        "company": "Wildberries",
        "title": "Стажёр фронтенд-разработчик",
        "stack": "JavaScript, Vue.js, TypeScript",
        "city": "Москва",
        "remote": 0,
        "salary": "от 45 000 ₽",
        "description": "Разработка интерфейсов маркетплейса. Vue.js, TypeScript.",
        "url": "https://wildberries.ru/career",
        "deadline": "15.07.2026",
    },
    # Kaspersky
    {
        "company": "Kaspersky",
        "title": "Стажёр C/C++ разработчик",
        "stack": "C, C++, Linux",
        "city": "Москва",
        "remote": 0,
        "salary": "от 50 000 ₽",
        "description": "Разработка антивирусного ядра и системного ПО.",
        "url": "https://safeboard.kaspersky.ru",
        "deadline": "01.07.2026",
    },
    {
        "company": "Kaspersky",
        "title": "Стажёр по кибербезопасности",
        "stack": "Python, Linux, Networking",
        "city": "Москва",
        "remote": 0,
        "salary": "от 45 000 ₽",
        "description": "Исследование угроз, анализ вредоносного ПО, SOC.",
        "url": "https://safeboard.kaspersky.ru",
        "deadline": "01.07.2026",
    },
    # Positive Technologies
    {
        "company": "Positive Technologies",
        "title": "Стажёр Python-разработчик",
        "stack": "Python, Django, PostgreSQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 40 000 ₽",
        "description": "Разработка инструментов кибербезопасности на Python.",
        "url": "https://www.ptsecurity.com/ru-ru/career",
        "deadline": "15.08.2026",
    },
    # Авито
    {
        "company": "Авито",
        "title": "Стажёр бэкенд-разработчик",
        "stack": "Go, PHP, PostgreSQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 55 000 ₽",
        "description": "Разработка сервисов крупнейшей доски объявлений. Go, микросервисы.",
        "url": "https://start.avito.ru",
        "deadline": "30.06.2026",
    },
    {
        "company": "Авито",
        "title": "Стажёр ML Engineer",
        "stack": "Python, PyTorch, SQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 55 000 ₽",
        "description": "ML-модели для поиска, рекомендаций и антифрода.",
        "url": "https://start.avito.ru",
        "deadline": "30.06.2026",
    },
    # Контур
    {
        "company": "СКБ Контур",
        "title": "Стажёр .NET-разработчик",
        "stack": "C#, .NET, PostgreSQL",
        "city": "Екатеринбург",
        "remote": 0,
        "salary": "от 35 000 ₽",
        "description": "Разработка облачных бухгалтерских сервисов на .NET.",
        "url": "https://kontur.ru/career",
        "deadline": "01.08.2026",
    },
    {
        "company": "СКБ Контур",
        "title": "Стажёр фронтенд-разработчик",
        "stack": "TypeScript, React, CSS",
        "city": "Екатеринбург",
        "remote": 0,
        "salary": "от 35 000 ₽",
        "description": "Разработка UI-компонентов и интерфейсов продуктов Контура.",
        "url": "https://kontur.ru/career",
        "deadline": "01.08.2026",
    },
    #МТС
    {
        "company": "МТС",
        "title": "Стажёр Java-разработчик",
        "stack": "Java, Spring, Oracle",
        "city": "Москва",
        "remote": 0,
        "salary": "от 40 000 ₽",
        "description": "Разработка биллинговых и телекоммуникационных систем.",
        "url": "https://career.mts.ru",
        "deadline": "31.07.2026",
    },
    {
        "company": "МТС",
        "title": "Стажёр Data Scientist",
        "stack": "Python, ML, SQL, Spark",
        "city": "Москва",
        "remote": 1,
        "salary": "от 45 000 ₽",
        "description": "ML-модели для рекомендательных систем и аналитики.",
        "url": "https://career.mts.ru",
        "deadline": "31.07.2026",
    },
    #Газпромнефть
    {
        "company": "Газпромнефть",
        "title": "Стажёр Python-разработчик",
        "stack": "Python, Django, Docker",
        "city": "Санкт-Петербург",
        "remote": 0,
        "salary": "от 45 000 ₽",
        "description": "Цифровизация нефтегазовой отрасли. Python, внутренние платформы.",
        "url": "https://career.gazprom-neft.ru",
        "deadline": "15.07.2026",
    },
    #Huawei
    {
        "company": "Huawei Russia",
        "title": "Стажёр C++ разработчик",
        "stack": "C++, Linux, Algorithms",
        "city": "Москва",
        "remote": 0,
        "salary": "от 70 000 ₽",
        "description": "R&D центр Huawei. Разработка системного ПО, компиляторы, ОС.",
        "url": "https://career.huawei.ru",
        "deadline": "30.06.2026",
    },
    #1С
    {
        "company": "1С",
        "title": "Стажёр-разработчик 1С",
        "stack": "1С, SQL",
        "city": "Москва",
        "remote": 0,
        "salary": "от 30 000 ₽",
        "description": "Разработка и доработка конфигураций 1С:Предприятие.",
        "url": "https://1c.ru/career",
        "deadline": "31.08.2026",
    },
    #Selectel
    {
        "company": "Selectel",
        "title": "Стажёр Go-разработчик",
        "stack": "Go, Linux, Docker",
        "city": "Санкт-Петербург",
        "remote": 1,
        "salary": "от 50 000 ₽",
        "description": "Разработка облачной инфраструктуры. Go, Kubernetes, IaC.",
        "url": "https://selectel.ru/career",
        "deadline": "30.06.2026",
    },
    #Сбермаркет (Купер)
    {
        "company": "Купер",
        "title": "Стажёр Ruby-разработчик",
        "stack": "Ruby, Rails, PostgreSQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 50 000 ₽",
        "description": "Разработка сервисов e-grocery на Ruby on Rails.",
        "url": "https://kuper.ru/career",
        "deadline": "15.07.2026",
    },
    #Samokat (Самокат)
    {
        "company": "Самокат",
        "title": "Стажёр Python-разработчик",
        "stack": "Python, FastAPI, Redis",
        "city": "Москва",
        "remote": 1,
        "salary": "от 45 000 ₽",
        "description": "Бэкенд-разработка для сервиса быстрой доставки.",
        "url": "https://samokat.ru/career",
        "deadline": "01.07.2026",
    },
    #Циан
    {
        "company": "Циан",
        "title": "Стажёр Python-разработчик",
        "stack": "Python, Django, PostgreSQL",
        "city": "Москва",
        "remote": 1,
        "salary": "от 50 000 ₽",
        "description": "Разработка платформы для аренды и продажи недвижимости.",
        "url": "https://cian.ru/career",
        "deadline": "31.07.2026",
    },
    #Lamoda
    {
        "company": "Lamoda",
        "title": "Стажёр Go-разработчик",
        "stack": "Go, gRPC, Docker",
        "city": "Москва",
        "remote": 0,
        "salary": "от 45 000 ₽",
        "description": "Разработка микросервисов fashion e-commerce на Go.",
        "url": "https://www.lamoda.ru/career",
        "deadline": "15.07.2026",
    },
]

async def seed():
    await init_db()
    for item in INTERNSHIPS:
        await add_internship(**item)
    print(f"Загружено {len(INTERNSHIPS)} стажировок в базу данных.")


if __name__ == "__main__":
    asyncio.run(seed())
